### ISSUE TITLE
Font enlarged with enabled Markdown plugin

### ISSUE THREAD

**Issue by jonpas** [AlfredoRamos/phpbb-ext-markdown#12]
PHP version: `7.2.19`
phpBB version: `3.2.7`
Markdown version: `1.0.0`

As soon as I enabled the Markdown plugin and update or create any post, that post gets enlarged font, as seen on the image below.

![](https://i.imgur.com/95WJpmZ.png)
_Left updated post with extension enabled, right old post._

**Comment by AlfredoRamos** [comment]
Hi @jonpas 

That's a style issue.

When this extension is enabled, the text is wrapped in a `<p>` tag. You don't mention the style you're using, but you can add the following snippet in any style sheet:

```css
/* Reset paragraph font size */
.postbody .content p {
	font-size: 1em;
}
```

That will reset the font size to be the same as its parent (`.content`).

If your style inherits from prosilver, you could add the above at the end of the file:

`{PHPBB_ROOT}/styles/prosilver/theme/content.css`

Let me know if it fixes the issue for you.

**Comment by jonpas** [comment]
Awesome, that does help, thank you!

**Comment by AlfredoRamos** [comment]
Hi,

Try replacing the previous code I shared with the following:

```css
/* Reset paragraph font size */
.postbody .content p,
.postbody .signature p {
	font-size: 1em;
}

/* Remove paragraph bottom margin in lists */
.postbody .content li p,
.postbody .signature li p {
	margin-bottom: 0;
}
```

That will fix both issues in posts, private messages and user signatures.

In the next version (1.1.0 probably) I will add support for my Imgur extension. It adds a style sheet (`ext/alfredoramos/markdown/styles/all/theme/css/markdown.css`) where you could add those changes in a future, to avoid modifying core files.

I don't know why prosilver does those changes, but I might need to add a FAQ entry, because there's some issues with headings too.

Thanks for the reports.

**Comment by jonpas** [comment]
Great, thanks a lot. I will report if I find any more inconsistencies so they can be included in the FAQ.

**Comment by jonpas** [comment]
I have tested your last commits, works very well, except one remaining issue with polls.

Here is the fix, feel free to put it into this repo, fork is not worth it for this small change. :)
```css
.content .polls p {
	margin-bottom: 0;
	line-height: 0;
}
```
